services:
  # Backend API service
  - type: web
    name: website-grader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health

  # Frontend service
  - type: web
    name: website-grader-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://website-grader-api.onrender.com 