services:
  # Backend API service
  - type: web
    name: website-grader-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.1
      - key: PORT
        value: 5000

  # Frontend React service
  - type: web
    name: website-grader
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: REACT_APP_API_URL
        value: https://website-grader-backend.onrender.com 