services:
  # Backend API service
  - type: web
    name: website-grader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production

  # Frontend static site
  - type: web
    name: website-grader-frontend
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 